name: Relay Control

on:
  schedule:
    - cron: '0 * * * *'  # Menjalankan setiap satu jam
  workflow_dispatch:

jobs:
  relay:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kode
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Menggunakan Node.js versi terbaru

    - name: Aktifkan Relay
      run: |
        # Menggunakan variabel lingkungan untuk token API
        TOKEN="$TOKEN_API"
        
        # Mengaktifkan relay
        curl -X POST "https://sgp1.blynk.cloud/external/api/update?token=$TOKEN&v1=1"
        
    - name: Wait for 20 Seconds
      uses: softprops/action-sleep@v1
      with:
        seconds: 20
        
    - name: Matikan Relay
      run: |
        # Menggunakan variabel lingkungan untuk token API
        TOKEN="$TOKEN_API"
        
        # Mematikan relay
        curl -X POST "https://sgp1.blynk.cloud/external/api/update?token=$TOKEN&v1=0"
