name: Relay Control

on:
  schedule:
    - cron: '0 * * * *'  # Menjalankan setiap satu jam
  workflow_dispatch:

jobs:
  relay:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kode
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Menggunakan Node.js versi terbaru

    - name: Aktifkan Relay
      run: |
        curl -X POST "https://sgp1.blynk.cloud/external/api/update?token=hsoqoqt9FAJb7B_CkMv9qHe5ei94zPUp&v1=1"
        
        # Menambahkan penundaan selama 20 detik menggunakan JavaScript
        node -e "setTimeout(() => {}, 20000)"
        
        curl -X POST "https://sgp1.blynk.cloud/external/api/update?token=hsoqoqt9FAJb7B_CkMv9qHe5ei94zPUp&v1=0"
